---
- name: Install OS dep pkgs
  become: true
  become_user: root
  ansible.builtin.command: apk add --no-cache --virtual=.build-dependencies wget ca-certificates
  changed_when: false

- name: Downloading {{ alpine_glibc_shim_key_url }} to {{ alpine_glibc_shim_key_path }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ alpine_glibc_shim_key_url }}'
    dest: '{{ alpine_glibc_shim_key_path }}'
    mode: '644'

- name: Downloading v{{ alpine_glibc_shim_ver }} pkgs from {{ alpine_glibc_shim_mirror }}...
  become: true
  become_user: root
  with_items: '{{ alpine_glibc_shim_pkg_prefixes }}'
  ansible.builtin.get_url:
    url: '{{ alpine_glibc_shim_mirror_ver }}/{{ item }}-{{ alpine_glibc_shim_ver }}.apk'
    dest: '{{ alpine_glibc_shim_tmp_dir | default("/tmp") }}/{{ item }}-{{ alpine_glibc_shim_ver }}.apk'
    checksum: '{{ alpine_glibc_shim_checksums[alpine_glibc_shim_ver][item] }}'
    mode: '644'

- name: Installing v{{ alpine_glibc_shim_ver }} pkgs...
  become: true
  become_user: root
  with_items: '{{ alpine_glibc_shim_pkg_prefixes }}'
  ansible.builtin.command: apk add --no-cache /tmp/{{ item }}-{{ alpine_glibc_shim_ver }}.apk
  changed_when: false

- name: Fix locales...
  become: true
  become_user: root
  when: alpine_glibc_shim_generate_locale.enabled
  ansible.builtin.command: >-
    /usr/glibc-compat/bin/localedef
    -i {{ alpine_glibc_shim_generate_locale.i }}
    -f {{ alpine_glibc_shim_generate_locale.f }}
    {{ alpine_glibc_shim_generate_locale.i }}.{{ alpine_glibc_shim_generate_locale.f -}}
  changed_when: false

- name: Template default local for sh
  become: true
  become_user: root
  with_items:
    - f: locale.sh
      d: /etc/profile.d
      m: '644'
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'

- name: Cleaning up v{{ alpine_glibc_shim_ver }} pkgs...
  become: true
  become_user: root
  with_items: '{{ alpine_glibc_shim_pkg_prefixes }}'
  ansible.builtin.file:
    path: '{{ alpine_glibc_shim_tmp_dir | default("/tmp") }}/{{ item }}-{{ alpine_glibc_shim_ver }}.apk'
    state: absent

- name: Cleanup...
  become: true
  become_user: root
  with_items:
    - .build-dependencies
  ansible.builtin.command: apk del {{ item }}
  changed_when: false
